server:
  port:
    8765

spring:
  application:
    name:
      cloud
  cloud:
    gateway:
      routes:
        - id: tasks
          uri: http://localhost:8080/
          predicates:
            - Path=/tasks/**
