global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "web-microservice"
    metrics_path: "actuator/prometheus"
    basic_auth:
      username: "user"
      password: "password"
    static_configs:
      - targets: [ "localhost:8080" ]

  - job_name: "rest-microservice"
    metrics_path: "actuator/prometheus"
    static_configs:
      - targets: [ "localhost:8081" ]