server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: tasks
          uri: http://localhost:8080/
          predicates:
            - Path=/tasks/**

        - id: rest
          uri: http://localhost:8081/
          predicates:
            - Path=/rest/**
